// src/views/Payments.vue
<template>

<div>



 
        <Navbar />
     

   <div class="cypherpunk-background section bg-slate-etica slate-min-height-65 text-white  pb-8">
     <div class="w-container pt-8">

      <h1 class="title font-primary-title color-primary mb-4" style="font-family: dotgothicregular;font-size: 45px;color: #d0d0d0;">
        Payments Overview
      </h1>
      
      <HorizontalNav 
          class="mb-8"
         v-bind:activeSection="activeSection" 
         v-bind:activeColor="'green'" 
         v-bind:buttonClickedCallback="onHorizontalNavClicked" 
         v-bind:buttonNamesArray="['Pool Balance Stats','Pool mints','Batched Payments' ]"
   
       />
        



        <div v-if="poolData && poolStatus && statsPayment && activeSection=='Pool Balance Stats'"  class="overflow-x-auto mb-4">
            <div class="my-4">
            <div v-if="poolName" style="color:green;"> {{ poolName }} is Active </div>              
               <div style="color: rgb(133, 251, 15);" v-if="statsPayment">Total ETI owed: {{rawAmountToFormatted(statsPayment.actual_total_coins_owed, 18 ) }} ETI [awaiting to reach the minimum payout]</div>
               <div style="color: rgb(31, 208, 75);" v-if="statsPayment">Total ETI in next Batch: {{rawAmountToFormatted(statsPayment.actual_total_next_coins_batchs , 18 ) }} ETI [total coins reached minimum payout, included next batchs]</div>

               <span v-if="statsPayment.createdAt">Last update: {{ statsPayment.createdAt }} </span>
              
              <div>Minting Account Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('solutions')" target="_blank" v-bind:href="getExplorerBaseURLFromType('solutions') + 'address/' + poolData.mintingAddress  "> {{poolData.mintingAddress}}  </a> </div>
              <div v-if="poolStatus.mintingAccountBalances">Minting address Balance: {{rawAmountToFormatted(poolStatus.mintingAccountBalances['ETH'] , 18 ) }} EGAZ</div>
              <div v-if="poolStatus.mintingAccountBalances">Minting address Balance: {{rawAmountToFormatted(poolStatus.mintingAccountBalances['token'], 18)}} ETI</div>
              <span>(Eti mined are immediately sent to reward process)</span>
            </div>
            <div class="my-4">
              <div>Payments Accounts Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('payments')" target="_blank" v-bind:href="getExplorerBaseURLFromType('payments') + 'address/' + poolData.paymentsAddress  "> {{poolData.paymentsAddress}} </a> </div>
              <div>Payments Network Name: {{poolData.paymentsNetwork}}</div>
              <div v-if="poolStatus.paymentsAccountBalances">Payments Balance EGAZ: {{rawAmountToFormatted(poolStatus.paymentsAccountBalances['ETH'],18)}} EGAZ (ETH)</div>

              <div v-if="poolData.batchedPaymentsContractAddress">Batched Payments Contract Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('payments')" target="_blank" v-bind:href="getExplorerBaseURLFromType('payments') + 'address/' + poolData.batchedPaymentsContractAddress  ">  {{poolData.batchedPaymentsContractAddress}}  </a> </div>
              <div v-if="poolStatus.paymentsAccountBalances" style="color: #aad0aa;">Mining Pool Balance: {{rawAmountToFormatted(poolStatus.paymentsAccountBalances['token'], 18)}} ETI</div>
              
            </div>
            <div class="my-4">
              <div>Minimum User Balance For Payment: {{rawAmountToFormatted(poolData.minBalanceForPayment,18)}} ETI</div>
            </div>
        </div> 

        <div v-if="poolStatus && activeSection=='Pool mints'" class="overflow-x-auto  mb-4">
          
          <div   class="box  background-secondary overflow-x-auto" style="  min-height:480px;">
        <div class='subtitle'> </div>
        <table class='table w-full'>

          <thead>
            <tr >
              <td class="px-1"> EpochCount # </td>
              <td class="px-1"> TransactionHash </td>
              <td class="px-1"> Status </td>
              <td class="px-1"> Block reward </td>
            </tr>
          </thead>

          <tbody>
            <tr v-for="(item, index) in poolMints" v-bind:key="index">
                <td>
                  <a v-bind:href='item.url' >
                        <span style="color: #ffffff;">  {{ item.epochCount }} </span>
                  </a>
                </td>
                <td class="px-1"> 
                  <a v-bind:href='"https://www.eticascan.org/tx/"+item.transactionHash' >
                        <span style="color: #527b7a;">  {{ shortenTransactionHash(item.transactionhash) }}  </span>
                  </a> 
                </td>
                <td class="px-1"> 
                      <span style="color: rgb(54, 179, 97);">  {{ getstatusname(item.poolstatus) }}  </span>
                </td>
                <td class="px-1"> 
                        <span v-if="index % 2 === 0" style="color: rgb(54, 179, 97);">  +{{ item.blockreward }} ETI </span>
                        <span v-else-if="index % 3 === 0" style="color:rgb(75, 176, 91);">  +{{ item.blockreward }} ETI </span>
                        <span v-else style="color: rgb(129, 221, 135);">  +{{ item.blockreward }} ETI </span>
                </td>
            </tr> 
          </tbody>
        </table>

      </div>
          
        </div> 


          

        <div v-if="activeSection =='Batched Payments'" class="mb-4">

        <section>
          <TransactionsTable
            class="mb-4"
            label="Batched Payments" 
            v-bind:transactionsList="recentPaymentTx"
          />
        </section>

        </div>

     </div>


    
   </div>
    

  <Footer    />

</div>
</template>

<style scoped>

/*
.cypherpunk-background {
  background-image: linear-gradient(90deg, rgba(100, 100, 100, 0.1) 1px, transparent 1px), linear-gradient(rgba(255, 255, 255, 0.1) 1px, transparent 1px);
background-size: 20px 20px;
}
.cypherpunk-background {
background-image: linear-gradient(90deg, rgba(100, 100, 100, 0.09) 1px, transparent 1px), linear-gradient(rgba(111, 93, 93, 0.1) 1px, transparent 1px);
background-size: 20px 20px;
}
*/

.cypherpunk-background {
background-image: linear-gradient(90deg, rgba(79, 238, 22, 0.09) 1px, transparent 1px), linear-gradient(rgba(111, 93, 93, 0.1) 1px, transparent 1px);
background-size: 20px 20px;
}

</style>


<script>
import Navbar from './components/Navbar.vue';
import AppPanel from './components/AppPanel.vue';
import VerticalNav from './components/VerticalNav.vue'
import Footer from './components/Footer.vue';
 

import TransactionsTable from './components/TransactionsTable.vue';
import HashrateChart from './components/HashrateChart.vue';

import HorizontalNav from './components/HorizontalNav.vue';

import SocketHelper from '../js/socket-helper'

 import FrontendHelper from '../js/frontend-helper';
 

import MathHelper from '../js/math-helper'

export default {
  name: 'Accounts',
  props: [],
  components: {Navbar,AppPanel,VerticalNav,Footer,TransactionsTable, HorizontalNav},
  data() {
    return {
      poolName: null,
      poolData: null,
      poolStatus: null,
      statsPayment: null,
      activeSection: 'Pool Balance Stats',
      accountList: [] ,
      poolMints: [],
      recentPaymentTx:[]

    }
  },
 

  created(){
     this.socketHelper = new SocketHelper()
      
      setInterval(this.pollSockets.bind(this),240000)


      this.socketsListener = this.socketHelper.initSocket()
     
     

        this.socketsListener.on('poolName', (name) => {   
            this.poolName = name;
        });

       this.socketsListener.on('poolData', (data) => {   
            this.poolData = data 
        });

         this.socketsListener.on('poolStatus', (data) => {   
            this.poolStatus = data 
            
        });

        this.socketsListener.on('statsPayment', (data) => {   
            if(data && data.length > 0){
                this.statsPayment = data[0]
            }        
        });

        this.socketsListener.on('statsPayment', (data) => {   
            if(data && data.length > 0){
                this.statsPayment = data[0]
            }        
        });

        this.socketsListener.on('poolMints', (data) => {   
            if(data && data.length > 0){
                this.poolMints = data
            }        
        });

        this.socketsListener.on('recentPayments', (data) => {  
            this.recentPaymentTx=data
            
            this.recentPaymentTx.map( x => this.addExplorerUrl(x, 'payments')  )

         });

      this.pollSockets()
  },
  methods: {
    pollSockets(){
      this.socketHelper.emitEvent('getPoolName')
      this.socketHelper.emitEvent('getPoolData')
      this.socketHelper.emitEvent('getPoolStatus')
      this.socketHelper.emitEvent('getStatsPayment')
      this.socketHelper.emitEvent('getPoolMints', {nbpoolmints: 50})
      this.socketHelper.emitEvent('getRecentPayments')
    },

    rawAmountToFormatted(amount, decimals){
      return MathHelper.rawAmountToFormatted(amount,decimals)
    },

    onHorizontalNavClicked(item){
     
      this.activeSection = item

    },

    getstatusname(_status){

      if(_status == 2){
        return 'Processed (rewards awarded)';
      }
      else if(_status == 1){
        return 'Processed (rewards awarded)';
      }
      else {
        return 'Unprocessed';
      }

      },

    addExplorerUrl(txData, txType){

      
      if(!this.poolData) return ; 
      
      const solutionsNetworkName = this.poolData.mintingNetwork

      const paymentsNetworkName = this.poolData.paymentsNetwork

   
      
      let baseURL = ''
 
      if(txType == 'payments'){
        baseURL =  FrontendHelper.getExplorerBaseURL(paymentsNetworkName)
      }else{
        baseURL = FrontendHelper.getExplorerBaseURL(solutionsNetworkName) 
      }



      txData.txURL=baseURL.concat('tx/').concat(txData.txHash)

    },

    getExplorerBaseURLFromType(txType){

      if(!this.poolData) return null; 
      
      const solutionsNetworkName = this.poolData.mintingNetwork

      const paymentsNetworkName = this.poolData.paymentsNetwork

     if(txType == 'payments'){
        return FrontendHelper.getExplorerBaseURL(paymentsNetworkName)
      }else{
        return FrontendHelper.getExplorerBaseURL(solutionsNetworkName) 
      }

 
    },

    shortenTransactionHash(hash) {
      if(hash){

       const prefix = hash.substring(0, 6);
       const suffix = hash.substring(hash.length - 6);
       return prefix + "..." + suffix;

      }
      else {

        return '';

      }
    
    }

 

  }
}
</script>

// frontend-new/src/pages/Payments.jsx
import React from 'react';
import SectionTitle from '../components/SectionTitle';
import DataCard from '../components/DataCard';
import DataRow from '../components/DataRow';
import DataTable from '../components/DataTable';
import StatusBadge from '../components/StatusBadge';
import LoadingSkeleton from '../components/LoadingSkeleton';
import { usePayments } from '../hooks/usePayments';
import { usePoolOverview } from '../hooks/usePoolOverview';
import {
  formatNumber,
  truncateAddress,
  rawToFormatted,
  mintStatusLabel,
  timeAgo,
} from '../lib/formatters';
import { ETICASCAN_URL } from '../config/constants';

export default function Payments() {
  const { data: payData, isLoading: payLoading, isError: payError } = usePayments();
  const { data: overview, isLoading: ovLoading, isError: ovError } = usePoolOverview();

  const statsPayment = payData?.statsPayment;
  const poolMints = payData?.poolMints || [];
  const recentPayments = payData?.recentPaymentTxs || payData?.recentPayments || [];

  const poolData = overview?.poolData;
  const poolStatus = overview?.poolStatus;

  return (
    <div>
      <div className="os-heading">
        <h1 className="os-heading-title">PAYMENTS</h1>
      </div>

      {/* Pool Balance Stats */}
      <div className="os-block">
        <SectionTitle color="emerald">Pool Balance Stats</SectionTitle>

        {payLoading || ovLoading ? (
          <LoadingSkeleton type="card" />
        ) : payError || ovError ? (
          <p className="faded">Failed to load payment data.</p>
        ) : (
          <DataCard accent="linear-gradient(90deg, var(--os-emerald), var(--os-cyan))">
            <div className="os-metrics col-2" style={{ marginBottom: '1rem' }}>
              <div className="os-metric">
                <div className="os-metric-label">Total ETI Owed</div>
                <div className="os-metric-value emerald">
                  {rawToFormatted(statsPayment?.actual_total_coins_owed)} ETI
                </div>
              </div>
              <div className="os-metric">
                <div className="os-metric-label">Next Batch</div>
                <div className="os-metric-value emerald">
                  {rawToFormatted(statsPayment?.actual_total_next_coins_batchs)} ETI
                </div>
              </div>
            </div>

            {statsPayment?.createdAt && (
              <DataRow label="Last Updated" className="faded">
                {statsPayment.createdAt}
              </DataRow>
            )}
            <DataRow label="Minting Address">
              <a
                href={`${ETICASCAN_URL}/address/${poolData?.mintingAddress}`}
                target="_blank"
                rel="noreferrer"
                className="os-link-cyan"
              >
                {truncateAddress(poolData?.mintingAddress, 10)}
              </a>
            </DataRow>
            <DataRow label="Minting EGAZ">
              {rawToFormatted(poolStatus?.mintingAccountBalances?.ETH)} EGAZ
            </DataRow>
            <DataRow label="Minting ETI" className="emerald">
              {rawToFormatted(poolStatus?.mintingAccountBalances?.token)} ETI
            </DataRow>
            <DataRow label="Payments Address">
              <a
                href={`${ETICASCAN_URL}/address/${poolData?.paymentsAddress}`}
                target="_blank"
                rel="noreferrer"
                className="os-link-cyan"
              >
                {truncateAddress(poolData?.paymentsAddress, 10)}
              </a>
            </DataRow>
            {poolData?.paymentsNetwork && (
              <DataRow label="Payments Network" className="faded">
                {poolData.paymentsNetwork}
              </DataRow>
            )}
            <DataRow label="Payments EGAZ">
              {rawToFormatted(poolStatus?.paymentsAccountBalances?.ETH)} EGAZ
            </DataRow>
            {poolData?.batchedPaymentsContractAddress && (
              <DataRow label="Batched Payments Contract">
                <a
                  href={`${ETICASCAN_URL}/address/${poolData.batchedPaymentsContractAddress}`}
                  target="_blank"
                  rel="noreferrer"
                  className="os-link-cyan"
                >
                  {truncateAddress(poolData.batchedPaymentsContractAddress, 10)}
                </a>
              </DataRow>
            )}
            <DataRow label="Mining Pool Balance" className="emerald">
              {rawToFormatted(poolStatus?.paymentsAccountBalances?.token)} ETI
            </DataRow>
            <DataRow label="Min Payout" className="emerald">
              {rawToFormatted(poolData?.minBalanceForPayment)} ETI
            </DataRow>
          </DataCard>
        )}
      </div>

      {/* Pool Mints */}
      <div className="os-block">
        <SectionTitle color="cyan">Pool Mints</SectionTitle>

        {payLoading ? (
          <LoadingSkeleton type="table" />
        ) : payError ? (
          <p className="faded">Failed to load pool mints.</p>
        ) : (
          <DataTable
            columns={[
              { label: 'Epoch' },
              { label: 'Tx Hash' },
              { label: 'Status' },
              { label: 'Block Reward', align: 'right' },
            ]}
            data={poolMints}
            emptyMessage="No pool mints yet"
            renderRow={(item, idx) => (
              <tr key={idx} className="os-table-row">
                <td className="py-3 px-3">
                  <span className="cyan">{formatNumber(item.epochCount)}</span>
                </td>
                <td className="py-3 px-3">
                  <a
                    href={`${ETICASCAN_URL}/tx/${item.transactionhash}`}
                    target="_blank"
                    rel="noreferrer"
                    className="os-link-cyan"
                  >
                    {truncateAddress(item.transactionhash, 10)}
                  </a>
                </td>
                <td className="py-3 px-3">
                  <StatusBadge status={mintStatusLabel(item.poolstatus)} />
                </td>
                <td className="py-3 px-3 right">
                  <span className="emerald">{rawToFormatted(item.blockreward)} ETI</span>
                </td>
              </tr>
            )}
          />
        )}
      </div>

      {/* Batched Payments */}
      <div className="os-block">
        <SectionTitle color="orange">Batched Payments</SectionTitle>

        {payLoading ? (
          <LoadingSkeleton type="table" />
        ) : payError ? (
          <p className="faded">Failed to load batched payments.</p>
        ) : (
          <DataTable
            columns={[
              { label: 'Block' },
              { label: 'Tx Hash' },
              { label: 'Status' },
            ]}
            data={recentPayments}
            emptyMessage="No batched payments yet"
            renderRow={(item, idx) => (
              <tr key={idx} className="os-table-row">
                <td className="py-3 px-3">
                  <span className="faded">{formatNumber(item.block)}</span>
                </td>
                <td className="py-3 px-3">
                  <a
                    href={`${ETICASCAN_URL}/tx/${item.txHash}`}
                    target="_blank"
                    rel="noreferrer"
                    className="os-link-cyan"
                  >
                    {truncateAddress(item.txHash, 10)}
                  </a>
                </td>
                <td className="py-3 px-3">
                  <StatusBadge status={item.status} />
                </td>
              </tr>
            )}
          />
        )}
      </div>
    </div>
  );
}
