// frontend-new/src/templates/overview-a/Overview.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { poolData, poolNameAndUrl, formatNumber, truncateAddress, rawToFormatted, recentPaymentsBatched } from '../../mock-data';

const TABS = ['Mining Data', 'Getting Started', 'Pool Status', 'Recent Transactions'];

const EXPLORER = 'https://eticascan.org/';

function removeProtocol(url) {
  if (!url) return '';
  return url.replace(/^https?:\/\//, '');
}

/* ── Shared inline styles ── */
const s = {
  page: {
    background: '#000000',
    color: '#d4d4d4',
    minHeight: '100vh',
    fontFamily: "'Space Mono', monospace",
    fontSize: 14,
    lineHeight: 1.7,
  },
  container: {
    maxWidth: 960,
    margin: '0 auto',
    padding: '2rem 1.5rem',
  },
  backLink: {
    color: '#06b6d4',
    textDecoration: 'none',
    fontSize: 12,
    letterSpacing: '0.04em',
  },
  title: {
    color: '#d4d4d4',
    fontSize: 32,
    fontWeight: 400,
    margin: '1.5rem 0 1.25rem',
    fontFamily: "'Space Mono', monospace",
  },
  tabBar: {
    display: 'flex',
    flexWrap: 'wrap',
    marginBottom: '2rem',
  },
  tab: (active) => ({
    padding: '0.45rem 1.1rem',
    fontSize: 12,
    fontFamily: "'Space Mono', monospace",
    letterSpacing: '0.03em',
    border: '1px solid #d4d4d4',
    marginLeft: -1,
    cursor: 'pointer',
    transition: 'background 0.15s, color 0.15s',
    background: active ? '#22c55e' : 'transparent',
    color: active ? '#000000' : '#d4d4d4',
  }),
  separator: {
    height: 1,
    background: '#1c1c1c',
    margin: '1rem 0',
  },
  sectionTitle: {
    color: '#22c55e',
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    marginBottom: '0.5rem',
    marginTop: '1.5rem',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    padding: '0.3rem 0',
    borderBottom: '1px solid #1c1c1c',
    gap: '1rem',
    flexWrap: 'wrap',
  },
  label: {
    color: '#a0a0a0',
    fontSize: 13,
    flexShrink: 0,
  },
  value: {
    color: '#d4d4d4',
    fontSize: 13,
    textAlign: 'right',
    wordBreak: 'break-all',
  },
  greenValue: {
    color: '#22c55e',
    fontSize: 13,
    textAlign: 'right',
    wordBreak: 'break-all',
  },
  cyanLink: {
    color: '#06b6d4',
    textDecoration: 'none',
  },
  smallGreen: {
    color: 'rgb(164, 255, 3)',
    fontSize: 11,
    wordBreak: 'break-all',
    lineHeight: 1.5,
  },
  note: {
    color: '#868585',
    fontSize: 12,
    fontStyle: 'italic',
  },
  portCard: {
    border: '1px solid #2a2a2a',
    padding: '0.75rem 1rem',
    flex: '1 1 200px',
    minWidth: 180,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 13,
  },
  th: {
    textAlign: 'left',
    padding: '0.5rem 0.75rem',
    borderBottom: '1px solid #2a2a2a',
    color: '#22c55e',
    fontSize: 11,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontWeight: 600,
  },
  td: {
    padding: '0.45rem 0.75rem',
    borderBottom: '1px solid #141414',
    color: '#d4d4d4',
  },
};

function Row({ label, children, green }) {
  return (
    <div style={s.row}>
      <span style={s.label}>{label}</span>
      <span style={green ? s.greenValue : s.value}>{children}</span>
    </div>
  );
}

function Separator() {
  return <div style={s.separator} />;
}

/* ══════════ TAB: Mining Data ══════════ */
function MiningDataTab() {
  const { poolStatus, miningContract } = poolData;
  const mintBal = poolStatus.mintingAccountBalances;
  const payBal = poolStatus.paymentsAccountBalances;
  const bonus = poolStatus.poolFeesMetrics.poolRewardsBonus;

  return (
    <div>
      {/* Pool active status */}
      <div style={{ color: '#22c55e', marginBottom: '0.25rem' }}>
        {poolNameAndUrl.poolName} is Active
        {bonus > 0 && (
          <span style={{ color: '#04ffab' }}>
            {' '}(Bonus Activated: +{bonus * 100}% on all mining rewards)
          </span>
        )}
      </div>

      {/* Minting Account */}
      <div style={s.sectionTitle}>Minting Account</div>
      <Row label="Address">
        <a style={s.cyanLink} href={EXPLORER + 'address/' + poolData.mintingAddress} target="_blank" rel="noreferrer">
          {poolData.mintingAddress}
        </a>
      </Row>
      <Row label="Network">{poolData.mintingNetwork}</Row>
      <Row label="EGAZ Balance" green>{rawToFormatted(mintBal.ETH, 18)} EGAZ</Row>
      <Row label="ETI Balance" green>{rawToFormatted(mintBal.token, 18)} ETI</Row>
      <div style={s.note}>(ETI mined are immediately sent to reward process)</div>

      <Separator />

      {/* Payments Account */}
      <div style={s.sectionTitle}>Payments Account</div>
      <Row label="Address">
        <a style={s.cyanLink} href={EXPLORER + 'address/' + poolData.paymentsAddress} target="_blank" rel="noreferrer">
          {poolData.paymentsAddress}
        </a>
      </Row>
      <Row label="Network">{poolData.paymentsNetwork}</Row>
      <Row label="EGAZ Balance" green>{rawToFormatted(payBal.ETH, 18)} EGAZ</Row>
      <Row label="Batched Payments Contract">
        <a style={s.cyanLink} href={EXPLORER + 'address/' + poolData.batchedPaymentsContractAddress} target="_blank" rel="noreferrer">
          {poolData.batchedPaymentsContractAddress}
        </a>
      </Row>
      <Row label="Mining Pool Balance ETI" green>{rawToFormatted(payBal.token, 18)} ETI</Row>

      <Separator />

      {/* Block & Payment info */}
      <Row label="Last Known Block Number">{formatNumber(poolData.ethBlockNumber)}</Row>
      <Row label="Minimum User Balance For Payment" green>{rawToFormatted(poolData.minBalanceForPayment, 18)} ETI</Row>
      <div style={s.note}>
        Low Balance Payments: every 24 hours for balances between <b>0.01 ETI</b> and <b>{rawToFormatted(poolData.minBalanceForPayment, 18)} ETI</b>
      </div>

      <Separator />

      {/* Mining Contract Data */}
      <div style={s.sectionTitle}>Mining Contract Data</div>
      <div style={{ ...s.row, flexDirection: 'column', alignItems: 'flex-start' }}>
        <span style={s.label}>Current Network RandomX Blob:</span>
        <span style={s.smallGreen}>{miningContract.randomxBlob}</span>
      </div>
      <Row label="Seedhash">
        <span style={{ color: 'rgb(6, 119, 55)' }}>{miningContract.randomxSeedhash}</span>
      </Row>
      <Row label="Challenge Number">{miningContract.challengeNumber}</Row>
      <Row label="epochCount" green>{formatNumber(miningContract.epochCount)}</Row>
      <Row label="Mining Difficulty" green>{formatNumber(miningContract.miningDifficulty)}</Row>
    </div>
  );
}

/* ══════════ TAB: Getting Started ══════════ */
function GettingStartedTab() {
  const ports = poolData.stratumPorts;

  return (
    <div>
      <div style={s.sectionTitle}>Miners</div>
      <Row label="XMRig">
        <a style={s.cyanLink} href="https://xmrig.com/" target="_blank" rel="noreferrer">https://xmrig.com/</a>
      </Row>
      <Row label="SRBMiner">
        <a style={s.cyanLink} href="https://github.com/doktor83/SRBMiner-Multi/releases" target="_blank" rel="noreferrer">https://github.com/doktor83/SRBMiner-Multi/releases</a>
      </Row>

      <Separator />

      <div style={s.note}>
        Instructions: Use same settings as Monero. Replace address with Etica address. Enter pool URL with mining port. Example: {removeProtocol(poolNameAndUrl.poolUrl)}:3333
      </div>

      <Separator />

      <div style={{ ...s.sectionTitle, fontSize: 18, fontWeight: 400, textTransform: 'none' }}>Connection Details</div>

      <Row label="Mining Pool Address">
        <span style={{ color: '#b3b3b3' }}>{poolNameAndUrl.poolUrl}</span>
      </Row>

      <Separator />

      <div style={{ ...s.sectionTitle, marginBottom: '0.75rem' }}>Mining Ports</div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 0 }}>
        {ports.map((p, i) => (
          <div key={p.port} style={{ ...s.portCard, borderLeft: i === 0 ? '1px solid #2a2a2a' : 'none' }}>
            <div style={{ color: '#22c55e', fontSize: 15, fontWeight: 700 }}>Port {p.port}</div>
            <div style={{ color: '#a0a0a0', fontSize: 12 }}>Starting Difficulty: <span style={{ color: '#22c55e' }}>{formatNumber(p.difficulty)}</span></div>
            <div style={{ color: '#d4d4d4', fontSize: 12 }}>{p.label}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ══════════ TAB: Pool Status ══════════ */
function PoolStatusTab() {
  const { poolStatus, stratumPorts } = poolData;
  const fees = poolStatus.poolFeesMetrics;

  return (
    <div>
      <div style={{ color: '#22c55e', marginBottom: '1rem' }}>
        Pool Status: {poolNameAndUrl.poolName} is Active
      </div>

      <div style={s.sectionTitle}>Stratum Ports</div>
      {stratumPorts.map((p) => (
        <Row key={p.port} label={`Port ${p.port}`}>
          Minimum Share Difficulty: <span style={{ color: '#22c55e' }}>{formatNumber(p.difficulty)}</span>
        </Row>
      ))}

      <Separator />

      <Row label="avgGasPriceGWei" green>{fees.avgGasPriceGWei}</Row>
      <Row label="Full Mining Reward" green>
        {Number.parseFloat(rawToFormatted(fees.miningRewardRaw, 18))} ETI
      </Row>
      <Row label="Current ETI/EGAZ ratio">
        {fees.token_Eth_Price_Ratio} (1 ETI for {(1 / fees.token_Eth_Price_Ratio).toFixed(4)} EGAZ)
      </Row>
      <Row label="poolBaseFeeFactor">{fees.poolBaseFee}</Row>
      {fees.poolRewardsBonus > 0 && (
        <Row label="Rewards Bonus" green>{fees.poolRewardsBonus}</Row>
      )}
    </div>
  );
}

/* ══════════ TAB: Recent Transactions ══════════ */
function RecentTransactionsTab() {
  return (
    <div>
      <div style={s.sectionTitle}>Recent Payments</div>
      <table style={s.table}>
        <thead>
          <tr>
            <th style={s.th}>Block</th>
            <th style={s.th}>TxHash</th>
            <th style={s.th}>Status</th>
          </tr>
        </thead>
        <tbody>
          {recentPaymentsBatched.map((tx, i) => (
            <tr key={i}>
              <td style={s.td}>{formatNumber(tx.block)}</td>
              <td style={s.td}>
                <a style={s.cyanLink} href={EXPLORER + 'tx/' + tx.txHash} target="_blank" rel="noreferrer">
                  {truncateAddress(tx.txHash, 10)}
                </a>
              </td>
              <td style={{
                ...s.td,
                color: tx.status === 'confirmed' ? '#22c55e' : '#f59e0b',
              }}>
                {tx.status}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/* ══════════ MAIN COMPONENT ══════════ */
export default function Overview() {
  const [activeTab, setActiveTab] = useState('Mining Data');

  return (
    <div style={s.page}>
      <div style={s.container}>
        {/* Back link */}
        <Link to="/templates" style={s.backLink}>&larr; Back to Templates</Link>

        {/* Title */}
        <h1 style={s.title}>Pool Overview</h1>

        {/* Tab bar */}
        <div style={s.tabBar}>
          {TABS.map((tab, i) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              style={{
                ...s.tab(activeTab === tab),
                ...(i === 0 ? { marginLeft: 0 } : {}),
              }}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Tab content */}
        {activeTab === 'Mining Data' && <MiningDataTab />}
        {activeTab === 'Getting Started' && <GettingStartedTab />}
        {activeTab === 'Pool Status' && <PoolStatusTab />}
        {activeTab === 'Recent Transactions' && <RecentTransactionsTab />}
      </div>
    </div>
  );
}

// src/views/Overview.vue
<template>

<div>



 
        <Navbar />
     

   <div class="cypherpunk-background section bg-slate-etica slate-min-height-65 text-white  pb-8">
     <div class="w-container pt-8">

       
 

      <h1 class="title font-primary-title color-primary mb-4" style="font-family: dotgothicregular;font-size: 45px;color: #d0d0d0;">
        Pool Overview
      </h1>
      

      
      <HorizontalNav 
          class="mb-8"
         v-bind:activeSection="activeSection" 
         v-bind:activeColor="'green'" 
         v-bind:buttonClickedCallback="onHorizontalNavClicked" 
         v-bind:buttonNamesArray="['Mining Data', 'Getting Started', 'Pool Status','Recent Transactions' ]"
   
       />
        



        <div v-if="poolData && poolStatus && activeSection=='Mining Data'"  class="overflow-x-auto mb-4">
            <div class="my-4">
            <div v-if="poolName" style="color:green;"> {{ poolName }} is Active <span v-if="poolStatus.poolFeesMetrics && poolStatus.poolFeesMetrics.poolRewardsBonus > 0" style="color: #04ffab;">(Bonus Activated: +{{poolStatus.poolFeesMetrics.poolRewardsBonus}}% on all mining rewards)</span></div>
              <div>Minting Account Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('solutions')" target="_blank" v-bind:href="getExplorerBaseURLFromType('solutions') + 'address/' + poolData.mintingAddress  "> {{poolData.mintingAddress}}  </a> </div>
              <div>Minting Network Name: {{poolData.mintingNetwork}}</div>
              <div v-if="poolStatus.mintingAccountBalances">Minting Balance: {{rawAmountToFormatted(poolStatus.mintingAccountBalances['ETH'] , 18 ) }} EGAZ</div>
              <div v-if="poolStatus.mintingAccountBalances">Minting Balance: {{rawAmountToFormatted(poolStatus.mintingAccountBalances['token'], 18)}} ETI</div>
              <span>(Eti mined are immediately sent to reward process)</span>
            </div>
            <div class="my-4">
              <div>Payments Accounts Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('payments')" target="_blank" v-bind:href="getExplorerBaseURLFromType('payments') + 'address/' + poolData.paymentsAddress  "> {{poolData.paymentsAddress}} </a> </div>
              <div>Payments Network Name: {{poolData.paymentsNetwork}}</div>
              <div v-if="poolStatus.paymentsAccountBalances">Payments Balance EGAZ: {{rawAmountToFormatted(poolStatus.paymentsAccountBalances['ETH'],18)}} EGAZ</div>

              <div v-if="poolData.batchedPaymentsContractAddress">Batched Payments Contract Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('payments')" target="_blank" v-bind:href="getExplorerBaseURLFromType('payments') + 'address/' + poolData.batchedPaymentsContractAddress  ">  {{poolData.batchedPaymentsContractAddress}}  </a> </div>
              <div v-if="poolStatus.paymentsAccountBalances">Mining Pool Balance: {{rawAmountToFormatted(poolStatus.paymentsAccountBalances['token'], 18)}} ETI</div>
              
            </div>
            <div class="my-4">
              <div>Last Known Block Number: {{poolData.ethBlockNumber}}</div>
              <div style="color: #04ffab;">Minimum User Balance For Payment: {{rawAmountToFormatted(poolData.minBalanceForPayment,18)}} ETI</div>
              <div style="color: #868585;">
                  <i>Low Balance Payments:</i> <i>every 24 hours for balances between <b>0.01 ETI</b> and 
                 <b> {{rawAmountToFormatted(poolData.minBalanceForPayment,18)}} ETI</b></i>
              </div>
            </div>
        </div> 

          

         <div v-if="poolData && poolData.miningContract && activeSection=='Mining Data'"  class="overflow-x-auto  mb-4">
           
            <div><span style="text-decoration:underline;">Current Network Randomx Blob:</span> 
              <br><span style="font-size:11px;color: rgb(164, 255, 3);">{{poolData.miningContract.randomxBlob}}</span>
            </div>
            <div>Current Network Randomx Seedhash: <span style="color: rgb(6, 119, 55);">{{poolData.miningContract.randomxSeedhash}}</span></div>
            <div>Current Challenge Number: <span>{{poolData.miningContract.challengeNumber}}</span></div>

            <div>epochCount: {{poolData.miningContract.epochCount}}</div> 

            <div style="text-decoration:underline;">Blockchain difficulty:</div>
            <div>Current ETI Mining Difficulty: {{poolData.miningContract.miningDifficulty}}</div>

        </div> 

        <div v-if="poolData && poolStatus && activeSection=='Getting Started'"  class="overflow-x-auto mb-4">


          <div>Miners</div>
          <div>XMRig: <a target="_blank" href="https://xmrig.com/" style="color:#135e56;">https://xmrig.com/</a></div>
          <div>SRBMiner: <a target="_blank" href="https://github.com/doktor83/SRBMiner-Multi/releases" style="color:#135e56;">https://github.com/doktor83/SRBMiner-Multi/releases</a></div>

          <br>
          <i>Instructions:</i>
          <i>Use same settings as monero. Replace address with Etica address. Enter pool url with mining port. Example: {{ poolUrl }}:3333</i>


          <h1 class="title font-primary-title color-primary mb-4" style="font-family: dotgothicregular;font-size: 24px;color: #d0d0d0;">
            Connection Details
          </h1>

          <div><span style="text-decoration:underline;">Mining Pool address:</span><span style="color:rgb(179, 179, 179);"> {{ poolUrl }}</span></div>
          
          <br>
          <div style="text-decoration:underline;">Mining Ports</div>
          <br>
          

        <div style="display:inline-flex">
          <div style="margin-right: 5%;border-right: solid 1px white;width: 296px;">
          <div>Port: <span style="color:#135e56;">3333</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;"> 400 000</span></div> 
          <div>Low-end CPU</div> 
          </div>

          <div style="margin-right: 5%;border-right: solid 1px white;width: 296px;">
          <div style="color:#135e56;">Port: <span style="color:#135e56;">55555</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;"> 500 000</span></div> 
          <div>Low-end CPU</div> 
          </div>

          <div style="margin-left: 5%;width: 296px;">
          <div>Port: <span style="color:#135e56;">7777</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;">1 000 000</span></div> 
          <div>High-end CPU</div>
          </div>

        </div>

        <div style="display:inline-flex">

          <div style="margin-left: 5%;width: 296px;">
          <div>Port: <span style="color:#135e56;">9999</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;">2 000 000</span></div> 
          <div>Very-High-end CPU</div>
          </div>
        </div>


        </div>


        <div v-if="poolStatus && activeSection=='Pool Status'" class="overflow-x-auto  mb-4">
          
          <div class="mb-4">
            <div v-if="poolName" style="color:green;">Pool status: {{ poolName }} is Active </div>
    
          </div>

          <h3>Stratum ports</h3>
          <div style="text-decoration:underline;">Port 3333:</div>
          <div>Minimum Shares Difficulty: 400 000</div> 
          <div style="text-decoration:underline;">Port 5555:</div>
          <div>Minimum Shares Difficulty: 500 000</div> 
          <div style="text-decoration:underline;">Port 7777:</div>
          <div>Minimum Shares Difficulty: 1 000 000</div> 
          <div style="text-decoration:underline;">Port 9999:</div>
          <div>Minimum Shares Difficulty: 2 000 000</div> 


          <div class="mb-4">avgGasPriceGWei: {{poolStatus.poolFeesMetrics.avgGasPriceGWei}}</div>
          
          
          <div>Full Mining Reward: {{Number.parseFloat(rawAmountToFormatted(poolStatus.poolFeesMetrics.miningRewardRaw,18))}} ETI</div>

         <!-- <div>miningRewardInEth: {{poolStatus.poolFeesMetrics.miningRewardInEth}}</div> -->

          <div>Current ETI/EGAZ ratio: {{poolStatus.poolFeesMetrics.token_Eth_Price_Ratio}} (1 <img src="@/assets/images/etica-logo-sanstexte.png" height="100"  alt="" class="w-6 m-2" style="margin-left: 0;margin-right: 0;position: relative;top: -0.2vh;"> for {{ 1 / poolStatus.poolFeesMetrics.token_Eth_Price_Ratio }} <img src="@/assets/images/egaz-logo.png" height="100"  alt="" class="w-6 m-2" style="margin-left: 0;margin-right: 0;position: relative;top: -0.2vh;">)</div>

           <div>poolBaseFeeFactor: {{poolStatus.poolFeesMetrics.poolBaseFee}}</div>

           <div v-if="poolStatus.poolFeesMetrics && poolStatus.poolFeesMetrics.poolRewardsBonus > 0">pool Rewards Bonus: {{poolStatus.poolFeesMetrics.poolRewardsBonus}}</div>
          
        </div> 


          

        <div v-if="activeSection =='Recent Transactions'" class="mb-4">

        <section>
          <TransactionsTable
            class="mb-4"
            label="Recent Payments" 
            v-bind:transactionsList="recentPaymentTx"
          />
        </section>


        </div>

       

 


     </div>


    
   </div>

   

 
    

  <Footer    />

</div>
</template>


<style scoped>

.cypherpunk-background {
background-image: linear-gradient(90deg, rgba(79, 238, 22, 0.09) 1px, transparent 1px), linear-gradient(rgba(111, 93, 93, 0.1) 1px, transparent 1px);
background-size: 20px 20px;
}

</style>


<script>
import Navbar from './components/Navbar.vue';
import AppPanel from './components/AppPanel.vue';
import VerticalNav from './components/VerticalNav.vue'
import Footer from './components/Footer.vue';
 

import TransactionsTable from './components/TransactionsTable.vue';
import HashrateChart from './components/HashrateChart.vue';

import HorizontalNav from './components/HorizontalNav.vue';

import SocketHelper from '../js/socket-helper'

 import FrontendHelper from '../js/frontend-helper';
 

import MathHelper from '../js/math-helper'

export default {
  name: 'Accounts',
  props: [],
  components: {Navbar,AppPanel,VerticalNav,Footer,TransactionsTable, HorizontalNav},
  data() {
    return {
      poolName: null,
      poolUrl: null,
      poolData: null,
      poolStatus: null,

      activeSection: 'Mining Data',

      accountList: [] ,

      recentPaymentTx:[] 
    }
  },
 

  created(){
     this.socketHelper = new SocketHelper()
      
      setInterval(this.pollSockets.bind(this),240000)


      this.socketsListener = this.socketHelper.initSocket()
     
     

        this.socketsListener.on('poolNameAndUrl', (data) => {   
            this.poolName = data.poolName;
            this.poolUrl = data.poolUrl;
        });

       this.socketsListener.on('poolData', (data) => {   
            this.poolData = data 
        });

         this.socketsListener.on('poolStatus', (data) => {   
            this.poolStatus = data 
            
        });

         this.socketsListener.on('recentPayments', (data) => {  
            this.recentPaymentTx=data
            
            this.recentPaymentTx.map( x => this.addExplorerUrl(x, 'payments')  )

        });

      this.pollSockets()
  },
  methods: {
    pollSockets(){
      this.socketHelper.emitEvent('getPoolNameAndUrl')
      this.socketHelper.emitEvent('getPoolData')
      this.socketHelper.emitEvent('getPoolStatus')
      this.socketHelper.emitEvent('getRecentPayments')
    },

    rawAmountToFormatted(amount, decimals){
      return MathHelper.rawAmountToFormatted(amount,decimals)
    },

    onHorizontalNavClicked(item){
     
      this.activeSection = item


    },

    addExplorerUrl(txData, txType){

      
      if(!this.poolData) return ; 
      
      const solutionsNetworkName = this.poolData.mintingNetwork

      const paymentsNetworkName = this.poolData.paymentsNetwork

   
      
      let baseURL = ''
 
      if(txType == 'payments'){
        baseURL =  FrontendHelper.getExplorerBaseURL(paymentsNetworkName)
      }else{
        baseURL = FrontendHelper.getExplorerBaseURL(solutionsNetworkName) 
      }



      txData.txURL=baseURL.concat('tx/').concat(txData.txHash)

    },

    getExplorerBaseURLFromType(txType){

      if(!this.poolData) return null; 
      
      const solutionsNetworkName = this.poolData.mintingNetwork

      const paymentsNetworkName = this.poolData.paymentsNetwork

     if(txType == 'payments'){
        return FrontendHelper.getExplorerBaseURL(paymentsNetworkName)
      }else{
        return FrontendHelper.getExplorerBaseURL(solutionsNetworkName) 
      }

 
    }

 

  }
}
</script>
