// frontend-new/src/templates/overview-12/Overview.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  poolData,
  poolNameAndUrl,
  formatNumber,
  truncateAddress,
  rawToFormatted,
  recentPaymentsBatched,
} from '../../mock-data';
import './styles.css';

/* ---------- Subcomponents ---------- */

function SectionTitle({ children }) {
  return <h2 className="tw-section-title">{children}</h2>;
}

function ExpandableHash({ label, value }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div className="mb-3">
      <div className="tw-label mb-1.5">{label}</div>
      <div
        className={`tw-mono-field ${expanded ? 'tw-expanded' : ''}`}
        onClick={() => setExpanded(!expanded)}
        title="Click to expand/collapse"
      >
        {value}
      </div>
    </div>
  );
}

function DataRow({ label, children, className = '' }) {
  return (
    <div className="tw-data-row">
      <span className="tw-data-key">{label}</span>
      <span className={`tw-data-val ${className}`}>{children}</span>
    </div>
  );
}

/* ---------- Tab: Mining Data ---------- */

function MiningDataTab() {
  const { miningContract, poolStatus } = poolData;

  return (
    <div className="space-y-6">
      {/* Pool Status */}
      <div className="flex items-center gap-2 mb-2">
        <span className="tw-status-dot" />
        <span className="text-sm font-semibold text-[#4ade80]">
          {poolNameAndUrl.poolName} is Active
        </span>
        {poolStatus.poolFeesMetrics.poolRewardsBonus > 0 && (
          <span className="text-xs text-[#f97316]">
            (Bonus Activated: +{poolStatus.poolFeesMetrics.poolRewardsBonus * 100}% on all mining rewards)
          </span>
        )}
      </div>

      {/* Minting + Payments side by side */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Minting Account */}
        <div className="tw-card p-5">
          <SectionTitle>Minting Account</SectionTitle>
          <DataRow label="Address">
            <a
              href={`https://eticascan.org/address/${poolData.mintingAddress}`}
              target="_blank"
              rel="noreferrer"
              className="tw-link-cyan"
            >
              {poolData.mintingAddress}
            </a>
          </DataRow>
          <DataRow label="Network">{poolData.mintingNetwork}</DataRow>
          <DataRow label="EGAZ Balance">
            {rawToFormatted(poolStatus.mintingAccountBalances.ETH)} EGAZ
          </DataRow>
          <DataRow label="ETI Balance" className="orange">
            {rawToFormatted(poolStatus.mintingAccountBalances.token)} ETI
          </DataRow>
          <p className="tw-note mt-3">(ETI mined are immediately sent to reward process)</p>
        </div>

        {/* Payments Account */}
        <div className="tw-card p-5">
          <SectionTitle>Payments Account</SectionTitle>
          <DataRow label="Address">
            <a
              href={`https://eticascan.org/address/${poolData.paymentsAddress}`}
              target="_blank"
              rel="noreferrer"
              className="tw-link-cyan"
            >
              {poolData.paymentsAddress}
            </a>
          </DataRow>
          <DataRow label="Network">{poolData.paymentsNetwork}</DataRow>
          <DataRow label="EGAZ Balance">
            {rawToFormatted(poolStatus.paymentsAccountBalances.ETH)} EGAZ
          </DataRow>
          <DataRow label="Batched Payments">
            <a
              href={`https://eticascan.org/address/${poolData.batchedPaymentsContractAddress}`}
              target="_blank"
              rel="noreferrer"
              className="tw-link-cyan"
            >
              {truncateAddress(poolData.batchedPaymentsContractAddress, 12)}
            </a>
          </DataRow>
          <DataRow label="Pool Balance" className="orange">
            {rawToFormatted(poolStatus.paymentsAccountBalances.token)} ETI
          </DataRow>
        </div>
      </div>

      {/* Block Info */}
      <div className="tw-card p-5">
        <DataRow label="Last Known Block">{formatNumber(poolData.ethBlockNumber)}</DataRow>
        <DataRow label="Min Payment" className="orange">
          {rawToFormatted(poolData.minBalanceForPayment)} ETI
        </DataRow>
        <p className="tw-note mt-3">
          Low Balance Payments: every 24 hours for balances between 0.01 ETI and{' '}
          {rawToFormatted(poolData.minBalanceForPayment)} ETI
        </p>
      </div>

      {/* Mining Contract */}
      <div className="tw-card p-5">
        <SectionTitle>Mining Contract</SectionTitle>
        <ExpandableHash label="RandomX Blob" value={miningContract.randomxBlob} />
        <ExpandableHash label="RandomX Seedhash" value={miningContract.randomxSeedhash} />
        <ExpandableHash label="Challenge Number" value={miningContract.challengeNumber} />
        <div className="grid grid-cols-2 gap-6 mt-4">
          <div>
            <p className="tw-label mb-1">Epoch Count</p>
            <p className="text-xl font-bold text-white">{formatNumber(miningContract.epochCount)}</p>
          </div>
          <div>
            <p className="tw-label mb-1">Mining Difficulty</p>
            <p className="text-xl font-bold text-white">{formatNumber(miningContract.miningDifficulty)}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ---------- Tab: Getting Started ---------- */

function GettingStartedTab() {
  return (
    <div className="space-y-6">
      <div className="tw-card p-5">
        <SectionTitle>Miners</SectionTitle>
        <div className="space-y-2 text-sm">
          <div>
            XMRig:{' '}
            <a href="https://xmrig.com/" target="_blank" rel="noreferrer" className="tw-link">
              https://xmrig.com/
            </a>
          </div>
          <div>
            SRBMiner:{' '}
            <a
              href="https://github.com/doktor83/SRBMiner-Multi/releases"
              target="_blank"
              rel="noreferrer"
              className="tw-link"
            >
              https://github.com/doktor83/SRBMiner-Multi/releases
            </a>
          </div>
        </div>

        <p className="tw-note mt-4">
          Instructions: Use same settings as Monero. Replace address with Etica address.
          Enter pool URL with mining port. Example:{' '}
          {poolNameAndUrl.poolUrl?.replace(/^https?:\/\//, '')}:3333
        </p>
      </div>

      <div className="tw-card p-5">
        <SectionTitle>Connection Details</SectionTitle>
        <DataRow label="Pool URL" className="orange">
          {poolNameAndUrl.poolUrl}
        </DataRow>
      </div>

      <div>
        <SectionTitle>Mining Ports</SectionTitle>
        <div className="tw-ports-grid">
          {poolData.stratumPorts.map((sp) => (
            <div key={sp.port} className="tw-card p-5 text-center">
              <div className="text-2xl font-bold text-white mb-1">
                <span className={`tw-port-${sp.port} text-xs font-semibold px-2 py-0.5 rounded`}>
                  {sp.port}
                </span>
              </div>
              <p className="tw-label mt-3">Starting Difficulty</p>
              <p className="text-sm font-bold text-white mt-1">{formatNumber(sp.difficulty)}</p>
              <p className="text-xs text-[#525252] mt-2">{sp.label}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ---------- Tab: Pool Status ---------- */

function PoolStatusTab() {
  const { poolStatus } = poolData;
  const fees = poolStatus.poolFeesMetrics;

  return (
    <div className="space-y-6">
      <div className="tw-card p-5">
        <div className="flex items-center gap-2 mb-4">
          <span className="tw-status-dot" />
          <span className="text-sm font-semibold text-[#4ade80]">
            Pool Status: {poolNameAndUrl.poolName} is Active
          </span>
        </div>

        <SectionTitle>Stratum Ports</SectionTitle>
        {poolData.stratumPorts.map((sp) => (
          <DataRow key={sp.port} label={`Port ${sp.port}`}>
            Minimum Shares Difficulty: {formatNumber(sp.difficulty)}
          </DataRow>
        ))}
      </div>

      <div className="tw-card p-5">
        <SectionTitle>Fees &amp; Rewards</SectionTitle>
        <DataRow label="Avg Gas Price">{fees.avgGasPriceGWei} GWei</DataRow>
        <DataRow label="Full Mining Reward" className="orange">
          {Number.parseFloat(rawToFormatted(fees.miningRewardRaw))} ETI
        </DataRow>
        <DataRow label="ETI/EGAZ Ratio">{fees.token_Eth_Price_Ratio}</DataRow>
        <DataRow label="Pool Base Fee">{fees.poolBaseFee}</DataRow>
        {fees.poolRewardsBonus > 0 && (
          <DataRow label="Rewards Bonus" className="green">
            +{fees.poolRewardsBonus * 100}%
          </DataRow>
        )}
      </div>
    </div>
  );
}

/* ---------- Tab: Recent Transactions ---------- */

function RecentTransactionsTab() {
  return (
    <div>
      <div className="tw-card p-5 overflow-hidden">
        <SectionTitle>Recent Payments</SectionTitle>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr>
                <th className="text-left py-3 px-3 tw-label font-medium">Block</th>
                <th className="text-left py-3 px-3 tw-label font-medium">TxHash</th>
                <th className="text-right py-3 px-3 tw-label font-medium">Status</th>
              </tr>
            </thead>
            <tbody>
              {recentPaymentsBatched.map((tx, idx) => (
                <tr key={idx} className="tw-table-row">
                  <td className="py-3 px-3 text-white font-medium">{tx.block}</td>
                  <td className="py-3 px-3">
                    <a
                      href={`https://eticascan.org/tx/${tx.txHash}`}
                      target="_blank"
                      rel="noreferrer"
                      className="tw-link-cyan font-mono text-xs"
                    >
                      {truncateAddress(tx.txHash, 12)}
                    </a>
                  </td>
                  <td className="py-3 px-3 text-right">
                    <span
                      className={`text-xs font-medium px-2 py-0.5 rounded ${
                        tx.status === 'confirmed'
                          ? 'text-[#4ade80] bg-[#4ade80]/5'
                          : 'text-[#fbbf24] bg-[#fbbf24]/5'
                      }`}
                    >
                      {tx.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

/* ---------- Main Overview ---------- */

const TABS = ['Mining Data', 'Getting Started', 'Pool Status', 'Recent Transactions'];

export default function Overview() {
  const [activeTab, setActiveTab] = useState('Mining Data');
  const { stratumPorts } = poolData;

  return (
    <div className="tw-root font-mono">
      {/* ========== HEADER ========== */}
      <header className="tw-header">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-5">
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-4">
              <img src="/images/eti-logo.png" alt="ETI" className="w-9 h-9" />
              <div>
                <div className="flex items-center gap-3">
                  <span className="text-lg font-bold text-white tracking-tight">
                    ETICA MINING POOL
                  </span>
                  <span className="flex items-center gap-1.5 text-xs font-medium text-[#4ade80] uppercase tracking-wider">
                    <span className="tw-status-dot" />
                    Active
                  </span>
                </div>
                <div className="text-[11px] text-[#525252] mt-0.5">
                  {poolNameAndUrl.poolUrl}
                </div>
              </div>
            </div>

            <div className="flex items-center gap-4">
              <input
                type="text"
                placeholder="0x... search miner"
                className="tw-search-input px-3 py-2 w-56 hidden sm:block"
                readOnly
              />
              <Link to="/templates" className="tw-back-link">
                &larr; templates
              </Link>
            </div>
          </div>

          <div className="flex items-center gap-2 mt-4 text-xs text-[#525252]">
            <span className="text-[#737373] mr-1">Ports:</span>
            {stratumPorts.map((sp, i) => (
              <span key={sp.port} className="flex items-center gap-1">
                <span className="text-[#a3a3a3] font-semibold">{sp.port}</span>
                <span className="text-[#404040]">{sp.label}</span>
                {i < stratumPorts.length - 1 && (
                  <span className="text-[#2a2a2a] mx-1">&middot;</span>
                )}
              </span>
            ))}
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
        {/* Page Title */}
        <h1 className="text-3xl font-bold text-white tracking-tight mb-6">
          Pool Overview
        </h1>

        {/* Tab Navigation */}
        <div className="tw-tabs">
          {TABS.map((tab) => (
            <button
              key={tab}
              className={`tw-tab ${activeTab === tab ? 'active' : ''}`}
              onClick={() => setActiveTab(tab)}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        {activeTab === 'Mining Data' && <MiningDataTab />}
        {activeTab === 'Getting Started' && <GettingStartedTab />}
        {activeTab === 'Pool Status' && <PoolStatusTab />}
        {activeTab === 'Recent Transactions' && <RecentTransactionsTab />}

        {/* Footer */}
        <footer className="pt-8 pb-8">
          <div className="tw-footer-line mb-6" />
          <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-[#525252]">
            <span className="font-mono text-[#404040] break-all">
              {poolData.smartContractAddress}
            </span>
          </div>
          <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-[#525252] mt-3">
            <span>
              Ports: <span className="text-[#737373]">3333 / 5555 / 7777 / 9999</span>
            </span>
            <span>
              Fee: <span className="text-[#737373]">{poolData.pool.poolFee}%</span>
            </span>
            <span>
              Min Payout:{' '}
              <span className="text-[#f97316]">{poolData.pool.minimumPayout} ETI</span>
            </span>
          </div>
          <p className="text-center text-xs text-[#2a2a2a] mt-4">
            Etica Mining Pool &mdash; Decentralized Protocol Research
          </p>
        </footer>
      </main>
    </div>
  );
}

// src/views/Overview.vue
<template>

<div>



 
        <Navbar />
     

   <div class="cypherpunk-background section bg-slate-etica slate-min-height-65 text-white  pb-8">
     <div class="w-container pt-8">

       
 

      <h1 class="title font-primary-title color-primary mb-4" style="font-family: dotgothicregular;font-size: 45px;color: #d0d0d0;">
        Pool Overview
      </h1>
      

      
      <HorizontalNav 
          class="mb-8"
         v-bind:activeSection="activeSection" 
         v-bind:activeColor="'green'" 
         v-bind:buttonClickedCallback="onHorizontalNavClicked" 
         v-bind:buttonNamesArray="['Mining Data', 'Getting Started', 'Pool Status','Recent Transactions' ]"
   
       />
        



        <div v-if="poolData && poolStatus && activeSection=='Mining Data'"  class="overflow-x-auto mb-4">
            <div class="my-4">
            <div v-if="poolName" style="color:green;"> {{ poolName }} is Active <span v-if="poolStatus.poolFeesMetrics && poolStatus.poolFeesMetrics.poolRewardsBonus > 0" style="color: #04ffab;">(Bonus Activated: +{{poolStatus.poolFeesMetrics.poolRewardsBonus}}% on all mining rewards)</span></div>
              <div>Minting Account Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('solutions')" target="_blank" v-bind:href="getExplorerBaseURLFromType('solutions') + 'address/' + poolData.mintingAddress  "> {{poolData.mintingAddress}}  </a> </div>
              <div>Minting Network Name: {{poolData.mintingNetwork}}</div>
              <div v-if="poolStatus.mintingAccountBalances">Minting Balance: {{rawAmountToFormatted(poolStatus.mintingAccountBalances['ETH'] , 18 ) }} EGAZ</div>
              <div v-if="poolStatus.mintingAccountBalances">Minting Balance: {{rawAmountToFormatted(poolStatus.mintingAccountBalances['token'], 18)}} ETI</div>
              <span>(Eti mined are immediately sent to reward process)</span>
            </div>
            <div class="my-4">
              <div>Payments Accounts Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('payments')" target="_blank" v-bind:href="getExplorerBaseURLFromType('payments') + 'address/' + poolData.paymentsAddress  "> {{poolData.paymentsAddress}} </a> </div>
              <div>Payments Network Name: {{poolData.paymentsNetwork}}</div>
              <div v-if="poolStatus.paymentsAccountBalances">Payments Balance EGAZ: {{rawAmountToFormatted(poolStatus.paymentsAccountBalances['ETH'],18)}} EGAZ</div>

              <div v-if="poolData.batchedPaymentsContractAddress">Batched Payments Contract Address: <a class="color-eticacyan" v-if="getExplorerBaseURLFromType('payments')" target="_blank" v-bind:href="getExplorerBaseURLFromType('payments') + 'address/' + poolData.batchedPaymentsContractAddress  ">  {{poolData.batchedPaymentsContractAddress}}  </a> </div>
              <div v-if="poolStatus.paymentsAccountBalances">Mining Pool Balance: {{rawAmountToFormatted(poolStatus.paymentsAccountBalances['token'], 18)}} ETI</div>
              
            </div>
            <div class="my-4">
              <div>Last Known Block Number: {{poolData.ethBlockNumber}}</div>
              <div style="color: #04ffab;">Minimum User Balance For Payment: {{rawAmountToFormatted(poolData.minBalanceForPayment,18)}} ETI</div>
              <div style="color: #868585;">
                  <i>Low Balance Payments:</i> <i>every 24 hours for balances between <b>0.01 ETI</b> and 
                 <b> {{rawAmountToFormatted(poolData.minBalanceForPayment,18)}} ETI</b></i>
              </div>
            </div>
        </div> 

          

         <div v-if="poolData && poolData.miningContract && activeSection=='Mining Data'"  class="overflow-x-auto  mb-4">
           
            <div><span style="text-decoration:underline;">Current Network Randomx Blob:</span> 
              <br><span style="font-size:11px;color: rgb(164, 255, 3);">{{poolData.miningContract.randomxBlob}}</span>
            </div>
            <div>Current Network Randomx Seedhash: <span style="color: rgb(6, 119, 55);">{{poolData.miningContract.randomxSeedhash}}</span></div>
            <div>Current Challenge Number: <span>{{poolData.miningContract.challengeNumber}}</span></div>

            <div>epochCount: {{poolData.miningContract.epochCount}}</div> 

            <div style="text-decoration:underline;">Blockchain difficulty:</div>
            <div>Current ETI Mining Difficulty: {{poolData.miningContract.miningDifficulty}}</div>

        </div> 

        <div v-if="poolData && poolStatus && activeSection=='Getting Started'"  class="overflow-x-auto mb-4">


          <div>Miners</div>
          <div>XMRig: <a target="_blank" href="https://xmrig.com/" style="color:#135e56;">https://xmrig.com/</a></div>
          <div>SRBMiner: <a target="_blank" href="https://github.com/doktor83/SRBMiner-Multi/releases" style="color:#135e56;">https://github.com/doktor83/SRBMiner-Multi/releases</a></div>

          <br>
          <i>Instructions:</i>
          <i>Use same settings as monero. Replace address with Etica address. Enter pool url with mining port. Example: {{ poolUrl }}:3333</i>


          <h1 class="title font-primary-title color-primary mb-4" style="font-family: dotgothicregular;font-size: 24px;color: #d0d0d0;">
            Connection Details
          </h1>

          <div><span style="text-decoration:underline;">Mining Pool address:</span><span style="color:rgb(179, 179, 179);"> {{ poolUrl }}</span></div>
          
          <br>
          <div style="text-decoration:underline;">Mining Ports</div>
          <br>
          

        <div style="display:inline-flex">
          <div style="margin-right: 5%;border-right: solid 1px white;width: 296px;">
          <div>Port: <span style="color:#135e56;">3333</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;"> 400 000</span></div> 
          <div>Low-end CPU</div> 
          </div>

          <div style="margin-right: 5%;border-right: solid 1px white;width: 296px;">
          <div style="color:#135e56;">Port: <span style="color:#135e56;">55555</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;"> 500 000</span></div> 
          <div>Low-end CPU</div> 
          </div>

          <div style="margin-left: 5%;width: 296px;">
          <div>Port: <span style="color:#135e56;">7777</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;">1 000 000</span></div> 
          <div>High-end CPU</div>
          </div>

        </div>

        <div style="display:inline-flex">

          <div style="margin-left: 5%;width: 296px;">
          <div>Port: <span style="color:#135e56;">9999</span></div>
          <div>Starting Difficulty: <span style="color:#135e56;">2 000 000</span></div> 
          <div>Very-High-end CPU</div>
          </div>
        </div>


        </div>


        <div v-if="poolStatus && activeSection=='Pool Status'" class="overflow-x-auto  mb-4">
          
          <div class="mb-4">
            <div v-if="poolName" style="color:green;">Pool status: {{ poolName }} is Active </div>
    
          </div>

          <h3>Stratum ports</h3>
          <div style="text-decoration:underline;">Port 3333:</div>
          <div>Minimum Shares Difficulty: 400 000</div> 
          <div style="text-decoration:underline;">Port 5555:</div>
          <div>Minimum Shares Difficulty: 500 000</div> 
          <div style="text-decoration:underline;">Port 7777:</div>
          <div>Minimum Shares Difficulty: 1 000 000</div> 
          <div style="text-decoration:underline;">Port 9999:</div>
          <div>Minimum Shares Difficulty: 2 000 000</div> 


          <div class="mb-4">avgGasPriceGWei: {{poolStatus.poolFeesMetrics.avgGasPriceGWei}}</div>
          
          
          <div>Full Mining Reward: {{Number.parseFloat(rawAmountToFormatted(poolStatus.poolFeesMetrics.miningRewardRaw,18))}} ETI</div>

         <!-- <div>miningRewardInEth: {{poolStatus.poolFeesMetrics.miningRewardInEth}}</div> -->

          <div>Current ETI/EGAZ ratio: {{poolStatus.poolFeesMetrics.token_Eth_Price_Ratio}} (1 <img src="@/assets/images/etica-logo-sanstexte.png" height="100"  alt="" class="w-6 m-2" style="margin-left: 0;margin-right: 0;position: relative;top: -0.2vh;"> for {{ 1 / poolStatus.poolFeesMetrics.token_Eth_Price_Ratio }} <img src="@/assets/images/egaz-logo.png" height="100"  alt="" class="w-6 m-2" style="margin-left: 0;margin-right: 0;position: relative;top: -0.2vh;">)</div>

           <div>poolBaseFeeFactor: {{poolStatus.poolFeesMetrics.poolBaseFee}}</div>

           <div v-if="poolStatus.poolFeesMetrics && poolStatus.poolFeesMetrics.poolRewardsBonus > 0">pool Rewards Bonus: {{poolStatus.poolFeesMetrics.poolRewardsBonus}}</div>
          
        </div> 


          

        <div v-if="activeSection =='Recent Transactions'" class="mb-4">

        <section>
          <TransactionsTable
            class="mb-4"
            label="Recent Payments" 
            v-bind:transactionsList="recentPaymentTx"
          />
        </section>


        </div>

       

 


     </div>


    
   </div>

   

 
    

  <Footer    />

</div>
</template>


<style scoped>

.cypherpunk-background {
background-image: linear-gradient(90deg, rgba(79, 238, 22, 0.09) 1px, transparent 1px), linear-gradient(rgba(111, 93, 93, 0.1) 1px, transparent 1px);
background-size: 20px 20px;
}

</style>


<script>
import Navbar from './components/Navbar.vue';
import AppPanel from './components/AppPanel.vue';
import VerticalNav from './components/VerticalNav.vue'
import Footer from './components/Footer.vue';
 

import TransactionsTable from './components/TransactionsTable.vue';
import HashrateChart from './components/HashrateChart.vue';

import HorizontalNav from './components/HorizontalNav.vue';

import SocketHelper from '../js/socket-helper'

 import FrontendHelper from '../js/frontend-helper';
 

import MathHelper from '../js/math-helper'

export default {
  name: 'Accounts',
  props: [],
  components: {Navbar,AppPanel,VerticalNav,Footer,TransactionsTable, HorizontalNav},
  data() {
    return {
      poolName: null,
      poolUrl: null,
      poolData: null,
      poolStatus: null,

      activeSection: 'Mining Data',

      accountList: [] ,

      recentPaymentTx:[] 
    }
  },
 

  created(){
     this.socketHelper = new SocketHelper()
      
      setInterval(this.pollSockets.bind(this),240000)


      this.socketsListener = this.socketHelper.initSocket()
     
     

        this.socketsListener.on('poolNameAndUrl', (data) => {   
            this.poolName = data.poolName;
            this.poolUrl = data.poolUrl;
        });

       this.socketsListener.on('poolData', (data) => {   
            this.poolData = data 
        });

         this.socketsListener.on('poolStatus', (data) => {   
            this.poolStatus = data 
            
        });

         this.socketsListener.on('recentPayments', (data) => {  
            this.recentPaymentTx=data
            
            this.recentPaymentTx.map( x => this.addExplorerUrl(x, 'payments')  )

        });

      this.pollSockets()
  },
  methods: {
    pollSockets(){
      this.socketHelper.emitEvent('getPoolNameAndUrl')
      this.socketHelper.emitEvent('getPoolData')
      this.socketHelper.emitEvent('getPoolStatus')
      this.socketHelper.emitEvent('getRecentPayments')
    },

    rawAmountToFormatted(amount, decimals){
      return MathHelper.rawAmountToFormatted(amount,decimals)
    },

    onHorizontalNavClicked(item){
     
      this.activeSection = item


    },

    addExplorerUrl(txData, txType){

      
      if(!this.poolData) return ; 
      
      const solutionsNetworkName = this.poolData.mintingNetwork

      const paymentsNetworkName = this.poolData.paymentsNetwork

   
      
      let baseURL = ''
 
      if(txType == 'payments'){
        baseURL =  FrontendHelper.getExplorerBaseURL(paymentsNetworkName)
      }else{
        baseURL = FrontendHelper.getExplorerBaseURL(solutionsNetworkName) 
      }



      txData.txURL=baseURL.concat('tx/').concat(txData.txHash)

    },

    getExplorerBaseURLFromType(txType){

      if(!this.poolData) return null; 
      
      const solutionsNetworkName = this.poolData.mintingNetwork

      const paymentsNetworkName = this.poolData.paymentsNetwork

     if(txType == 'payments'){
        return FrontendHelper.getExplorerBaseURL(paymentsNetworkName)
      }else{
        return FrontendHelper.getExplorerBaseURL(solutionsNetworkName) 
      }

 
    }

 

  }
}
</script>
