// src/views/components/Footer.vue
<template>
  <div class="bg-etica-footer">
    <div class="container-3 w-container">
      <div class="w-row">
        <div class="column-5 w-col w-col-4 w-col-small-4">
          <h3 class="heading-3 footer">Documentation</h3>


          <a href="https://www.eticaprotocol.org/viewwhitepaper" target="_blank" class="footer-link">White Paper</a>
          <a href="https://www.eticaprotocol.org/eticadocs/mining.html" target="_blank" class="footer-link">How to mine Etica</a>
          <a href="https://www.eticaprotocol.org/eticadocs/howitworks.html" target="_blank" class="footer-link">How it works</a>
          <a href="https://www.eticaprotocol.org/exchanges" target="_blank" class="footer-link">Exchanges</a>
          <a href="https://www.youtube.com/watch?v=IaIDSLBxzjg" target="_blank" class="footer-link">Create Etica Wallet (Metamask)</a>
          <a href="https://github.com/etica/etica-gui/releases" target="_blank" class="footer-link">Create Etica Wallet (GUI)</a>
          <a href="https://www.youtube.com/watch?v=tPljgu0rez0" target="_blank" class="footer-link">How to mine EGAZ</a>
      
        </div>
        <div class="column-6 w-col w-col-4 w-col-small-4">
          <h3 class="heading-3 footer">Community &amp; Social</h3>
          <a href="https://github.com/etica/eticapool" target="_blank" class="footer-link">Run this pool: Github</a>
          <a href="https://reddit.com/r/etica" target="_blank" class="footer-link">Reddit</a>
          <a href="https://discord.gg/CrTKpETKXc" target="_blank" class="footer-link">Discord</a>
          <a href="https://t.me/eticaprotocol" target="_blank" class="footer-link">Telegram</a>
          </div>
        <div class="column-7 w-col w-col-4 w-col-small-4 flex flex-col h-full">
        <h3 class="heading-3 footer">Explorers</h3>
        <a href="https://www.eticascan.org" target="_blank" class="footer-link">https://www.eticascan.org</a>
        <a href="http://explorer.etica-stats.org/" target="_blank" class="footer-link">http://explorer.etica-stats.org</a>
        <div class="flex-grow h-20">
         <a href="https://miningpoolstats.stream/etica" target="_blank" class="brand w-nav-brand w--current">
               <img src="@/assets/images/egaz-logo.png" height="100"  alt="" class="w-6 m-2">
            <div class=" inline-block text-xl text-white-100" style="position: relative;top: 0.75vh;color: white;">Egaz pools</div>
         </a>
        </div>
        <div style="display: inline-flex;">
        <img src="@/assets/images/github-mark-white.png" height="100"  alt="" class="w-6 m-2">
        <a href="https://github.com/etica/eticapool" target="_blank" class="footer-link" style="padding-top: 0.75vh;">Eticapool v 1.0.7</a>
        </div>

         </div>
      </div>
    </div>
  </div>
</template>


<script>


export default {
  name: 'Footer',
  props: [],
  data() {
    return {

    }
  },
  created(){

  },
  methods: {

  }
}
</script>

// frontend-new/src/components/Footer.jsx
import React from 'react';

const FOOTER_COLUMNS = [
  {
    heading: 'Documentation',
    links: [
      { label: 'White Paper', url: 'https://www.eticaprotocol.org/viewwhitepaper' },
      { label: 'How to mine Etica', url: 'https://www.eticaprotocol.org/eticadocs/mining.html' },
      { label: 'How it works', url: 'https://www.eticaprotocol.org/eticadocs/howitworks.html' },
      { label: 'Exchanges', url: 'https://www.eticaprotocol.org/exchanges' },
      { label: 'Create Etica Wallet (Metamask)', url: 'https://www.youtube.com/watch?v=IaIDSLBxzjg' },
      { label: 'Create Etica Wallet (GUI)', url: 'https://github.com/etica/etica-gui/releases' },
      { label: 'How to mine EGAZ', url: 'https://www.youtube.com/watch?v=tPljgu0rez0' },
    ],
  },
  {
    heading: 'Community & Social',
    links: [
      { label: 'Run this pool: Github', url: 'https://github.com/etica/eticapool' },
      { label: 'Reddit', url: 'https://reddit.com/r/etica' },
      { label: 'Discord', url: 'https://discord.gg/CrTKpETKXc' },
      { label: 'Telegram', url: 'https://t.me/eticaprotocol' },
    ],
  },
  {
    heading: 'Explorers',
    links: [
      { label: 'EticaScan', url: 'https://www.eticascan.org' },
      { label: 'Etica Stats Explorer', url: 'http://explorer.etica-stats.org/' },
      { label: 'Mining Pool Stats', url: 'https://miningpoolstats.stream/etica' },
      { label: 'Eticapool v4.0.17', url: 'https://github.com/etica/eticapool' },
    ],
  },
];

export default function Footer({ contractAddress, poolFee, minimumPayout }) {
  return (
    <footer className="pt-10 pb-8">
      <div className="os-footer-line mb-8" />

      <div className="os-footer-columns">
        {FOOTER_COLUMNS.map((col) => (
          <div key={col.heading}>
            <h4 className="os-footer-heading">{col.heading}</h4>
            {col.links.map((link) => (
              <a
                key={link.label}
                href={link.url}
                target="_blank"
                rel="noreferrer"
                className="os-footer-link"
              >
                {link.label}
              </a>
            ))}
          </div>
        ))}
      </div>

      <div className="os-footer-line mt-8 mb-4" />

      {contractAddress && (
        <div className="os-footer-meta">
          <span className="font-mono text-[#374151] break-all text-[10px]">
            {contractAddress}
          </span>
        </div>
      )}

      <div className="os-footer-meta mt-2">
        <span>Ports: <span className="text-[#6b7280]">3333 / 5555 / 7777 / 9999</span></span>
        {poolFee !== undefined && (
          <span>Fee: <span className="text-[#6b7280]">{poolFee}%</span></span>
        )}
        {minimumPayout !== undefined && (
          <span>Min Payout: <span className="text-[#34d399]">{minimumPayout} ETI</span></span>
        )}
      </div>

      <p className="os-footer-text mt-4">
        Etica Mining Pool &mdash; Science knows no country because knowledge belongs to Humanity
      </p>
    </footer>
  );
}
